#ifndef _LANG_H
#define _LANG_H

// Раскомментируйте только одну строку для выбора языка
#define LANG_UA
// #define LANG_RU
// #define LANG_EN

// ======================= УКРАЇНСЬКА =======================
#if defined(LANG_UA)
    #define STR_VERSION       "Програма КЛЕРК v 1.0 "
    #define D_N0              "рык "
    #define D_N1              "мысяць"
    #define D_N2              "день"
    #define D_N3              "годин"
    #define D_N4              "хвилин"
    #define S_N2              "Перыод"
    #define S_N3              "Режим"
    #define S_N4              "Накопич."
    #define BUTT01            "Запис"
    #define BUTT00            "Нема SD"
    #define BUTT1             "Час"
    #define BUTT2             "Налашт."
    #define BUTT3             "Вихыд"
    #define BUTT4             "Замына"
    #define BUTT5             "Скасув"
    #define STR_QUANTITY      "Кылькысть датчикыв "
    #define STR_NOT_FOUND     "Датчикыв не знайдено!"
    #define STR_DHT_OK        "DHT-21 пыдключен"
    #define STR_SAVE_DATA     "       ДАННЫ ЗБЕРЫГ         "
    #define STR_WRT_ERROR     "ПОМИЛКА ЗАПИСУ!"
    #define STR_NEW_LOG       "Новий лог створено"
    #define STR_LOG_APPEND    "Додавання журналу"
    #define STR_FILE_ERROR    "Помилка відкриття файлу"
    #define STR_SD_MISSING    "   SD карту не вставлено!   "
    #define STR_SD_DETECTED   "SD карта визначена "
// ========================= РУССКИЙ =========================
#elif defined(LANG_RU)
    #define STR_VERSION       "Программа КЛЕРК v 1.0"
    #define D_N0              "год "
    #define D_N1              "месяц"
    #define D_N2              "день"
    #define D_N3              "час"
    #define D_N4              "минут"
    #define S_N2              "Период"
    #define S_N3              "Режим"
    #define S_N4              "Накопл."
    #define BUTT01            "Запись"
    #define BUTT00            "Нет SD"
    #define BUTT1             "Время"
    #define BUTT2             "Устан."
    #define BUTT3             "Выход"
    #define BUTT4             "Изменить"
    #define BUTT5             "Отмена"
    #define STR_QUANTITY      "Количество датчиков"
    #define STR_NOT_FOUND     "Датчиков не найдено! "
    #define STR_DHT_OK        "DHT-21 подключен"
    #define STR_SAVE_DATA     "      ДАННЫЕ СОХРАНИЛ       "
    #define STR_WRT_ERROR     "ОШИБКА  ЗАПИСИ!"
    #define STR_NEW_LOG       " Создан новый лог "
    #define STR_LOG_APPEND    "Добавлена запись "
    #define STR_FILE_ERROR    " Ошибка открытия файла "
    #define STR_SD_MISSING    "   SD карта не вставлена!   "
    #define STR_SD_DETECTED   "SD карта определена"
// ========================= ENGLISH =========================
#elif defined(LANG_EN)
    #define STR_VERSION       "The CLERK program v1.0"
    #define D_N0              "year"
    #define D_N1              "month"
    #define D_N2              "day "
    #define D_N3              "hour"
    #define D_N4              "minut"
    #define S_N2              "Period"
    #define S_N3              "Mode"
    #define S_N4              "Storage"
    #define BUTT01            "Record"
    #define BUTT00            "No SD"
    #define BUTT1             "Time"
    #define BUTT2             "Set up"
    #define BUTT3             "Exit"
    #define BUTT4             "Change"
    #define BUTT5             "Cancel"
    #define STR_QUANTITY      "Sensors  amount    "
    #define STR_NOT_FOUND     "  No sensors found!  "
    #define STR_DHT_OK        "DHT-21 Connected"
    #define STR_SAVE_DATA     "         DATA SAVED         "
    #define STR_WRT_ERROR     "  WRITE ERROR! "
    #define STR_NEW_LOG       " New Log Created  "
    #define STR_LOG_APPEND    " Log Appending   "
    #define STR_FILE_ERROR    "    File Open Error    "
    #define STR_SD_MISSING    "    SD card is missing!     "
    #define STR_SD_DETECTED   " SD card detected  "
#endif

#endif // _LANG_H
